# Generated by Django 5.0.7 on 2024-07-25 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_room_room_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Room name")),
                (
                    "description",
                    models.TextField(max_length=250, verbose_name="Description"),
                ),
                ("capacity", models.PositiveSmallIntegerField(verbose_name="Capacity")),
            ],
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="checkIn",
            new_name="check_in_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="checkOut",
            new_name="check_out_date",
        ),
        migrations.RenameField(
            model_name="roomrate",
            old_name="dates",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="total_rooms",
        ),
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
        migrations.AddField(
            model_name="booking",
            name="payment",
            field=models.OneToOneField(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="core.payment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("occupied", "Occupied")],
                default=True,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "Mpesa"), ("paypal", "Paypal"), ("visa", "Visa")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_rooms",
                to="core.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="roomrate",
            name="rate",
            field=models.FloatField(verbose_name="Price per night"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="core.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="core.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomrate",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_rates",
                to="core.roomtype",
            ),
        ),
    ]
